version: '2.1'
services:
  dkrmon-server:
    container_name: dkrmon-server
    image: quaide/dkrmon:server
    volumes:
      - /media/sf_server/:/dkrmon/app/:rw
    ports:
     - "8080:5000"
    mem_limit: 128m
    tty: true
